version: "3"
services:
  db:
    image: postgres
    restart: always 
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
  test-db:
    image: postgres
    restart: always 
    ports:
      - "${TEST_DATABASE_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: "${TEST_DATABASE_PASSWORD}"