### GET All ToDos
GET http://localhost:3000/todos?limit=20&offset=10

### GET ToDo by id
GET http://localhost:3000/todos/3
content-type: application/json
Authorization: {{$dotenv API_KEY}}

### POST ToDo
POST http://localhost:3000/todos
content-type: application/json
Authorization: {{$dotenv API_KEY}}

{
    "name": "do the english homework",
    "description": "chapter 2",
    "tags": ["english", "homework"]
}

### PATCH ToDo
PATCH http://localhost:3000/todos/3
content-type: application/json
Authorization: {{$dotenv API_KEY}}

{
    "name": "do the biology homework",
    "description": "new description"
}

### DELETE ToDo
DELETE http://localhost:3000/todos/1
content-type: application/json
Authorization: {{$dotenv API_KEY}}
